<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Introduction" data-toc-modified-id="Introduction-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Introduction</a></span></li><li><span><a href="#Imports" data-toc-modified-id="Imports-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Imports</a></span></li><li><span><a href="#Scipy.optimize" data-toc-modified-id="Scipy.optimize-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Scipy.optimize</a></span><ul class="toc-item"><li><span><a href="#No-Jacobian" data-toc-modified-id="No-Jacobian-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>No Jacobian</a></span></li><li><span><a href="#With-Jacobian-of-only-function-+-(constraint-will-be-estimated-via-FDs)" data-toc-modified-id="With-Jacobian-of-only-function-+-(constraint-will-be-estimated-via-FDs)-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>With Jacobian of only function + (constraint will be estimated via FDs)</a></span></li><li><span><a href="#With-Jacobian-of-both-function-+-constraints" data-toc-modified-id="With-Jacobian-of-both-function-+-constraints-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>With Jacobian of both function + constraints</a></span></li></ul></li><li><span><a href="#References" data-toc-modified-id="References-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>References</a></span></li><li><span><a href="#Requirements" data-toc-modified-id="Requirements-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Requirements</a></span></li></ul></div>

# Introduction
<hr style = "border:2px solid black" ></hr>

<div class="alert alert-warning">
<font color=black>

**What?** How providing the Jacobian speed-up your solution time.
</font>
</div>

# Imports
<hr style = "border:2px solid black" ></hr>

In [1]:
import numpy as np
from scipy.optimize import minimize
import time
import numpy as np
from cvxpy import *  

# Scipy.optimize
<hr style = "border:2px solid black" ></hr>

## No Jacobian

In [2]:
matrix = np.array([[1.0, 1.5, -2.],
                   [0.5, 3.0, 2.5],
                   [1.0, 0.25, 0.75]])


def fct(x):
    return x.dot(matrix).dot(x)


x0 = np.ones(3) / 3
print(x0)
cons = ({'type': 'eq', 'fun': lambda x: x.sum() - 1.0})
bnds = [(0, 1)] * 3

w = minimize(fct, x0, method='SLSQP', bounds=bnds, constraints=cons)['x']

[0.33333333 0.33333333 0.33333333]


In [3]:
w

array([4.54545454e-01, 1.64104841e-15, 5.45454546e-01])

## With Jacobian of only function + (constraint will be estimated via FDs)

In [4]:
def fct_deriv(x):
    return 2 * matrix.dot(x)

In [5]:
minimize(fct, x0, method='SLSQP', jac=fct_deriv,
             bounds=bnds, constraints=cons)['x']

array([0.65517408, 0.17241322, 0.17241269])

## With Jacobian of both function + constraints

In [6]:
cons2 = ({'type': 'eq', 'fun': lambda x: x.sum() -
         1.0, 'jac': lambda x: np.ones_like(x)})

In [7]:
minimize(fct, x0, method='SLSQP', jac=fct_deriv,
             bounds=bnds, constraints=cons2)['x']

array([0.65517408, 0.17241322, 0.17241269])

# References
<hr style = "border:2px solid black" ></hr>

<div class="alert alert-warning">
<font color=black>

- https://stackoverflow.com/questions/43648073/what-is-the-fastest-way-to-minimize-a-function-in-python

</font>
</div>

# Requirements
<hr style = "border:2px solid black" ></hr>

In [8]:
%load_ext watermark
%watermark -v -iv

Python implementation: CPython
Python version       : 3.10.4
IPython version      : 8.3.0

json    : 2.0.9
autopep8: 1.7.0
numpy   : 1.21.6
cvxpy   : 1.2.1

